partisan/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^', include("party_rooms.urls", namespace="party")),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^registration/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^password/change/$', auth_views.password_change, name='password_change'),
]

party_rooms/urls.py
from django.conf.urls import url
from party_rooms.views import *
from party_rooms.ajax import *


urlpatterns = [
    url("^$", start_page, name="start_page"),
    url("^logout/", logout_view, name="logout"),
    url("^new_room/$", add_room, name="add_room"),
    url("^help/", help_view, name="help"),
    url("^profile/", profile_view, name="profile"),
    url("^room/(?P<room_id>\d+)/$", room, name="room"),
    url("^room/(?P<room_id>\d+)/auth/$", room_auth, name="room_auth"),
    url("^room/(?P<room_id>\d+)/enter/$", enter_room, name="enter_room"),
    url("^room/(?P<room_id>\d+)/settings/$", settings_room, name="settings_room"),
    url("^room/(?P<room_id>\d+)/change_description/$", modify_description, name="change_description"),
    url("^room/(?P<room_id>\d+)/change_password/$", change_password, name="change_password"),
    url("^room/(?P<room_id>\d+)/add_users/$", add_users, name="add_users"),
    url("^room/(?P<room_id>\d+)/place/$", place_room, name="place_room"),
    url("^room/(?P<room_id>\d+)/delete/$", delete_scenario, name="delete_scenario"),
    url("^room/(?P<room_id>\d+)/edit/$", edit_scenario, name="edit_scenario"),
    url("^room/(?P<room_id>\d+)/time/$", time_room, name="time_room"),
    url("^room/(?P<room_id>\d+)/result/$", result_room, name="result_room"),
    url("^room/(?P<room_id>\d+)/result/get/$", send_results, name="send_results"),
    url("^room/(?P<room_id>\d+)/new_place/$", add_place, name="add_place"),
    url("^room/(?P<room_id>\d+)/new_time/$", add_time, name="add_time"),
    url("^room/(?P<room_id>\d+)/place/new_answer/$", add_place_answer, name="add_place_answer"),
    url("^room/(?P<room_id>\d+)/time/new_answer/$", add_time_answer, name="add_time_answer"),
    url(r'^accounts/password_change/done/$', go_to_profile, name='password_change_done'),
]

party_rooms/models.py
from django.db import models
from django.contrib.auth.models import User
from party_rooms.logic import *


class Room(models.Model):
    usermade = models.BooleanField(default=True)
    room_users = models.ManyToManyField(User)
    admin_id = models.IntegerField(null=True)
    pass_hash = models.CharField(max_length=32, null=True)
    description = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.description

    def drop_caches(self):
        results = CachedResult.objects.filter(place__room_id=self.pk)
        Vote.mark_to_update(results)


class MeetingOption(models.Model):
    description = models.TextField(verbose_name="описание места")
    room = models.ForeignKey("Room")
    author_id = models.IntegerField(default=0)

    def __str__(self):
        return self.description

    class Meta:
        abstract = True
        unique_together = (("description", "room"),)


class MeetingTime(MeetingOption):
    pass


class MeetingPlace(MeetingOption):
    pass


class Conflict(models.Model):
    place = models.ForeignKey("MeetingPlace")
    time = models.ForeignKey("MeetingTime")


class Vote(models.Model):
    user = models.ForeignKey(User)
    possibility = models.IntegerField(choices=((UNDEFINED, "не задано"),
                                               (GOOD, "подходит"),
                                               (BAD, "не подходит"),
                                               (NOT_SURE, "возможно, подходит")),
                                      default=UNDEFINED)
    rating = models.IntegerField(choices=((UNDEFINED, "не задано"),
                                          (GOOD, "одобрительно"),
                                          (BAD, "неодобрительно"),
                                          (NOT_SURE, "нейтрально")),
                                 default=0)

    class Meta:
        abstract = True

    @staticmethod
    def mark_to_update(collection):
        for result in collection:
            result.need_calc = True
            result.save()


class PlaceVote(Vote):
    place = models.ForeignKey("MeetingPlace")

    def __str__(self):
        return "%s: %s" % (self.user, self.place)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(PlaceVote, self).save(force_insert, force_update, using, update_fields)
        self.mark_to_update(CachedResult.objects.filter(place=self.place))
        self.mark_to_update(UserCachedResult.objects.filter(user=self.user, place=self.place))


class TimeVote(Vote):
    time = models.ForeignKey("MeetingTime")

    def __str__(self):
        return "%s: %s" % (self.user, self.time)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(TimeVote, self).save(force_insert, force_update, using, update_fields)
        self.mark_to_update(CachedResult.objects.filter(time=self.time))
        self.mark_to_update(UserCachedResult.objects.filter(user=self.user, time=self.time))


class AbstractCachedResult(models.Model):
    need_calc = models.BooleanField(default=True)
    place = models.ForeignKey("MeetingPlace")
    time = models.ForeignKey("MeetingTime")
    result_rating = models.IntegerField(null=True)

    def get_room(self):
        return self.place.room

    class Meta:
        abstract = True


class CachedResult(AbstractCachedResult):
    participants = models.IntegerField(default=0)

    def calc(self):
        if self.need_calc:
            self.participants = 0
            self.result_rating = 0
            for user in self.get_room().room_users.all():
                user_result = UserCachedResult.objects.get_or_create(
                    user=user, place=self.place, time=self.time)[0].calc()
                self.result_rating += user_result.result_rating
                if user_result.is_possible:
                    self.participants += 1
            self.need_calc = False
            self.save()
        return self

    @staticmethod
    def update_all(room):
        for m_place in MeetingPlace.objects.filter(room=room):
            for m_time in MeetingTime.objects.filter(room=room):
                CachedResult.objects.get_or_create(place=m_place, time=m_time)[0].calc()

    class Meta:
        ordering = ["-result_rating"]


class UserCachedResult(AbstractCachedResult):
    is_possible = models.BooleanField(default=True)
    user = models.ForeignKey(User)

    def calc(self):
        if self.need_calc:
            place_vote = PlaceVote.objects.get_or_create(user=self.user, place=self.place)[0]
            time_vote = TimeVote.objects.get_or_create(user=self.user, time=self.time)[0]
            self.result_rating = calc_rating(place_vote, time_vote)
            self.is_possible = check_possibility(place_vote, time_vote)
            self.need_calc = False
            self.save()
        return self

party_rooms/forms.py
from django.forms import ModelForm
from registration.forms import RegistrationForm

from party_rooms.models import Room, User


class RoomForm(ModelForm):
    class Meta:
        model = Room
        exclude = []


class UserSettingsForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

party_rooms/views.py
import hashlib
import operator
from functools import reduce

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.views.decorators.http import require_POST

from party_rooms.forms import *
from party_rooms.models import Room, PlaceVote, TimeVote, User
from party_rooms.view_decorators import basic_view, find_room, check_room_auth


@login_required
@basic_view('party_rooms/all_rooms.html')
def start_page(request):
    return {'room_list': request.user.room_set.all}


@login_required
def add_room(request):
    if request.method == 'POST':
        description = request.POST['description']
        pass_hash = hashlib.md5(request.POST['password'].encode('utf-8')).hexdigest()
        new_room = Room.objects.create(pass_hash=pass_hash,
                                       description=description,
                                       admin_id=request.user.pk
                                       )
        new_room.room_users.add(request.user)
        new_room.save()
        return HttpResponseRedirect(reverse('party:room', kwargs={'room_id': new_room.pk}))
    else:
        return HttpResponseRedirect(reverse('party:start_page'))


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_generic.html')
def room(request, current_room):
    return {'room': current_room,
            'is_admin': (request.user.pk == current_room.admin_id)}


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_settings.html')
def settings_room(request, current_room):
    return {'room': current_room,
            'is_admin': (request.user.pk == current_room.admin_id),
            'form': RoomForm(instance=current_room),
            'possible_users': get_possible_users(current_room)}


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_for_place.html')
def place_room(request, current_room):
    def answer(offer):
        return offer, get_or_none(PlaceVote, user=request.user, place=offer)
    return {'room': current_room,
            'options': map(answer, current_room.meetingplace_set.all()),
            'is_admin': (request.user.pk == current_room.admin_id)}


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_for_time.html')
def time_room(request, current_room):
    def answer(offer):
        return offer, get_or_none(TimeVote, user=request.user, time=offer)
    return {'room': current_room,
            'options': map(answer, current_room.meetingtime_set.all()),
            'is_admin': (request.user.pk == current_room.admin_id)}


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_for_result.html')
def result_room(request, current_room):
    return {'room': current_room,
            'is_admin': (request.user.pk == current_room.admin_id)}


@login_required
@find_room
@basic_view('party_rooms/room_auth.html')
def room_auth(request, current_room):
    if request.user in current_room.room_users.all():
        return HttpResponseRedirect(reverse('party:room', kwargs={'room_id': current_room.pk}))
    return {'room': current_room}


@login_required
@require_POST
@find_room
def enter_room(request, current_room):
    if 'password' in request.POST:
        hash_sum = hashlib.md5(request.POST['password'].encode('utf-8')).hexdigest()
        if current_room.pass_hash == hash_sum:
            current_room.room_users.add(request.user)
            current_room.drop_caches()
            return HttpResponseRedirect(reverse('party:room', kwargs={'room_id': current_room.pk}))
    return HttpResponseRedirect(reverse('party:room_auth', kwargs={'room_id': current_room.pk}))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('party:start_page'))


def go_to_profile(request):
    return HttpResponseRedirect(reverse('party:profile'))


@login_required
@basic_view("party_rooms/help.html")
def help_view(request):
    return {}


@login_required
@basic_view("party_rooms/profile.html")
def profile_view(request):
    if request.method == "POST":
        form = UserSettingsForm(request.POST, instance=request.user)
        try:
            form.save()
            return {"saved": True, "form": form}
        except ValueError:
            return {"saved": False, "form": form}
    return {"saved": False, "form": UserSettingsForm(instance=request.user)}


def get_or_none(model, *args, **kwargs):
    try:
        return model.objects.get(*args, **kwargs)
    except model.DoesNotExist:
        return None


@login_required
@require_POST
@find_room
def add_users(request, current_room):
    if request.user.pk == current_room.admin_id:
        try:
            for user_id in request.POST['users']:
                user = User.objects.get(pk=int(user_id))
                current_room.room_users.add(user)
            current_room.drop_caches()
        except (KeyError, User.DoesNotExist):
            pass
    return HttpResponseRedirect(reverse('party:settings_room',  kwargs={'room_id': current_room.pk}))


def get_possible_users(current_room):
    def make_set(from_room):
        return set(from_room.room_users.all())
    admin = User.objects.get(pk=current_room.admin_id)
    user_set = reduce(operator.or_, map(make_set, admin.room_set.all()))
    return user_set.difference(set(current_room.room_users.all()))

templates/party_rooms/all_rooms.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/rooms.css' %}">
{% endblock %}

{%  block content %}
{% include 'party_rooms/fragment/modal_new_room.html' %}
{% include 'party_rooms/fragment/modal_enter_room.html' %}

    <div class="container">
        <h1>Комнаты</h1>
        <div class="btn-group btn-group-lg" role="group">
            <a class="btn btn-success" href="#new_room_modal" data-toggle="modal">Создать комнату</a>
            <a class="btn btn-primary" href="#enter_room_modal" data-toggle="modal">Присоединиться</a>
        </div>
        <div class="container">
            <table class="table table-condensed table-hover" id="all_rooms">
                <thead>
                    <tr>
                        <th>№</th>
                        <th>Описание</th>
                    </tr>
                </thead>
                <tbody class="rowlink" data-link="row">
                {% for room in room_list reversed %}
                    <tr>
                        <td><a href="{% url 'party:room' room.pk %}"></a>{{ room.pk }}</td>
                        <td>{{ room.description }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'bower_components/jasny-bootstrap/js/rowlink.js' %}"></script>
    <script>
        $('tbody.rowlink').rowlink()
    </script>
    <script src="{% static 'js/new_room.js' %}"></script>
    <script src="{% static 'js/join_room.js' %}"></script>
{% endblock %}

templates/party_rooms/help.html
{% extends "base.html" %}
{% load staticfiles %}
{% block style %}
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/one_room.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Справка</h1>
        {% include "party_rooms/fragment/room_help_message.html" %}
        <a href="{% url "party:start_page" %}"> На главную </a>
    </div>
{% endblock %}

templates/party_rooms/profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% block style %}
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/one_room.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h3>Профиль</h3>
        <div class="col-xs-8 col-xs-offst-2">
        {% if saved %}
            <p class="text-success">Изменения сохранены</p>
        {%  endif %}

            <form action="{% url 'party:profile' %}" method="POST" class="form">
                {% csrf_token %}
                {{ form|bootstrap }}

                <a href="{% url 'party:start_page' %}" class="btn btn-default">На главную</a>
                <a href="{% url 'password_change' %}" class="btn btn-default">
                    Сменить пароль <i class="fa fa-lock"></i></a>
                <input type="submit" value="Сохранить изменения" class="btn btn-primary">
            </form>
        </div>
    </div>
{% endblock %}

templates/party_rooms/room_auth.html
{% extends 'base.html' %}
{% block style %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block navbar %}{% endblock %}
{% block content %}

<div id="content" class="container">
    <div id="login_container">
        <h3>Комната № {{ room.pk }}</h3>
        <h4>Для первого входа в комнату необходим пароль.</h4>
        <h4>Его должен был сообщить пригласивший Вас человек.</h4>
        <form action="{% url 'party:enter_room' room.pk %}" method="post" accept-charset="utf-8" class="form-horizontal">
            {% csrf_token %}
            <div class="control-group">
                <label class="control-label col-xs-3" for="password">Пароль:</label>
                <div class="col-xs-9">
                    <input type="password" name="password" id="password" class="form-control">
                </div>
            </div>
            <br><br>
            <div class="control-group col-xs-offset-3 col-xs-9">
                <input type="submit" class="btn btn-primary" value="Войти">
                <a href="{% url 'party:start_page' %}" class="btn btn-default">На главную</a>
            </div>
        </form>

    </div>

    <div id="logo">
        <img src="{% static 'img/logo.svg' %}" alt="">
    </div>
</div>

{% endblock %}

templates/party_rooms/room_for_place.html
{% extends 'party_rooms/room_generic.html' %}
{% load staticfiles %}

{% block special %}
    <br>
    <a class="btn btn-success add_entry" href="#new_place_modal" data-toggle="modal">
        <i class="fa fa-plus-circle"></i> Предложить место
    </a>
    <div id="options">
        {% for option, choice in options %}
            {% include 'party_rooms/fragment/opinion_widget.html' %}
        {% endfor %}
    </div>
{% endblock %}

{% block global_vars %}
    <script>
        var ANSWER_URL = "{% url 'party:add_place_answer' room.pk %}";
        var TYPE = "place";
        var USER_ID = {{ request.user.pk }};
        var IS_ADMIN = false;
        {% if is_admin %}
            IS_ADMIN = true;
        {% endif %}
    </script>
{% endblock %}

{% block ws_script %}
    <script>
        ws_init({
            "chat_for_{{ room.pk }}": dummy,
            "place_for_{{ room.pk }}": handle_scenario
        }, {{ room.pk }}, "place");
    </script>
{% endblock %}

{% block extra_script %}
    <script>
        $('#place_button').addClass('btn-primary');
        reset_submit('#new_place_form');
        reset_submit('#delete_form');
        reset_submit('#edit_form');
    </script>
{% endblock %}

{% block modal %}
    {% include 'party_rooms/fragment/modal_add_place.html' %}
    {% include 'party_rooms/fragment/modal_delete_scenario.html' %}
    {% include 'party_rooms/fragment/modal_edit_scenario.html' %}
{% endblock %}

templates/party_rooms/room_for_result.html
{% extends 'party_rooms/room_generic.html' %}
{% load staticfiles %}

{% block special %}
    <h1 class="text-center" id="loading"><i class="fa fa-spinner loading"></i></h1>
    <div class="row hidden" id="result_table">
        <table class="table table-condensed" id="result_table">
            <thead>
                <tr>
                    <th>Место</th>
                    <th>Время</th>
                    <th>Возможные участники</th>
                    <th>Рейтинг</th>
                </tr>
            </thead>
            <tbody id="result_content">
            </tbody>
        </table>
    </div>

{% endblock %}

{% block extra_script %}
    <script src='{% static "js/result.js" %}'></script>
    <script>
        $('#result_button').addClass('btn-primary');
        $.ajax({
            url: '{% url "party:send_results" room.pk %}',
            data: {
                room: {{ room.pk }}
            },
            success: load_results
        });
    </script>
{% endblock %}

templates/party_rooms/room_for_time.html
{% extends 'party_rooms/room_generic.html' %}
{% load staticfiles %}

{% block style %}
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/one_room.css' %}">
{% endblock %}

{% block special %}
    <br>
    <a class="btn btn-success add_entry" href="#new_time_modal" data-toggle="modal">
        <i class="fa fa-plus-circle"></i> Предложить время
    </a>
    <div id="options">
        {% for option, choice in options %}
            {% include 'party_rooms/fragment/opinion_widget.html' %}
        {% endfor %}
    </div>
{% endblock %}

{% block ws_script %}
    <script>
        ws_init({
            "chat_for_{{ room.pk }}": dummy,
            "time_for_{{ room.pk }}": handle_scenario
        }, {{ room.pk }}, "time");
    </script>
{% endblock %}

{% block extra_script %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'bower_components/moment/min/moment-with-locales.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script>
        $('#time_button').addClass('btn-primary');
        reset_submit('#new_time_form');
        reset_submit('#delete_form');
        reset_submit('#edit_form');
        $('#dtpicker').datetimepicker({
            locale: 'ru'
        });
        // todo ws
    </script>
{% endblock %}

{% block modal %}
    {% include 'party_rooms/fragment/modal_add_time.html' %}
    {% include 'party_rooms/fragment/modal_delete_scenario.html' %}
    {% include 'party_rooms/fragment/modal_edit_scenario.html' %}
{% endblock %}

{% block global_vars %}
    <script>
        var ANSWER_URL = "{% url 'party:add_time_answer' room.pk %}";
        var TYPE = "time";
        var USER_ID = {{ request.user.pk }};
        var IS_ADMIN = false;
        {% if is_admin %}
            IS_ADMIN = true;
        {% endif %}
    </script>
{% endblock %}

templates/party_rooms/room_generic.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block style %}
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/one_room.css' %}">
{% endblock %}

{% block content %}
    {% block modal %}{% endblock %}
    {% if request.user in room.room_users.all %}
<div class="container">
    <h1>
        <a href="{% url 'party:room' room.pk %}" class="link">Комната № {{ room.pk }}</a>
        {% if is_admin %}
            <a href="{% url "party:settings_room" room.pk %}" title="настройки комнаты">
                <i class="fa fa-gear weak"></i>
            </a>
        {% endif %}
    </h1>

    <div>
        <div class="col-md-2">
            <h3>пользователи</h3>
            <div class="container">
            {% for room_user in room.room_users.all %}
                <p>{{ room_user.get_full_name|default:room_user.username }}</p>
            {% endfor %}
            </div>
        </div>
        <div class="col-md-7">
            <br>
            <div class="btn-group btn-group-lg" role="group">
                <a class="btn btn-default" href="{% url 'party:place_room' room.pk %}" id="place_button">
                    <i class="fa fa-map-signs"></i> выбор места</a>
                <a class="btn btn-default" href="{% url 'party:time_room' room.pk %}" id="time_button">
                    <i class="fa fa-clock-o"></i> выбор времени</a>
                <a class="btn btn-default" href="{% url 'party:result_room' room.pk %}" id="result_button">
                    <i class="fa fa-bar-chart"></i> результаты</a>
                <a class="btn btn-default" href="{% url 'party:start_page' %}" id="leave_button">
                    <i class="fa fa-sign-out"></i> выход</a>
            </div>
            {% block special %}
                {% include 'party_rooms/fragment/room_help_message.html' %}
            {% endblock %}
        </div>
        <div class="col-md-3">
{#            <h3>чат</h3>#}
{#            [в разработке]#}
        </div>
    </div>
</div>
    {% else %}
        Как Вы сюда попали?
    {% endif %}
{% endblock %}

{% block script %}
    <script type="text/javascript" src="{% static 'js/ws.js' %}"></script>

    {% block global_vars %}{% endblock %}
    <script src="{% static 'js/room.js' %}"></script>

    {% block ws_script %}
        <script>
            ws_init({
                "chat_for_{{ room.pk }}": dummy
            }, {{ room.pk }}, "");
        </script>
    {% endblock %}
    {% block extra_script %}
    {% endblock %}
{% endblock %}

templates/party_rooms/room_settings.html
{% extends "party_rooms/room_generic.html" %}
{% load staticfiles %}
{% block style %}
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap-select/dist/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/one_room.css' %}">
{% endblock %}
{% block modal %}
    {% include "party_rooms/fragment/modal_change_description.html" %}
    {% include "party_rooms/fragment/modal_invite_user.html" %}
    {% include "party_rooms/fragment/modal_change_password.html" %}
{% endblock %}

{% block special %}
    <div class="container">
        <h3>Настройки комнаты</h3>
        <div class="settings">
            <p><a href="#change_description_modal" data-toggle="modal"><i class="fa fa-edit"></i> Изменить описание</a></p>
            <p><a href="#change_password_modal" data-toggle="modal"><i class="fa fa-lock"></i> Изменить пароль</a></p>
            <p><a href="#invite_user_modal" data-toggle="modal"><i class="fa fa-users"></i> Пригласить пользователей</a></p>
        </div>
    </div>
{% endblock %}

{% block extra_script %}
    <script src="{% static 'bower_components/bootstrap-select/dist/js/bootstrap-select.js' %}"></script>
    <script>
        reset_submit('#change_description_form');
        reset_submit('#change_password_form');
    </script>
{% endblock %}