partisan/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^', include("party_rooms.urls", namespace="party")),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^registration/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^password/change/$', auth_views.password_change, name='password_change'),
]

party_rooms/urls.py
from django.conf.urls import url
from party_rooms.views import *
from party_rooms.ajax import *


urlpatterns = [
    url("^$", start_page, name="start_page"),
    url("^logout/", logout_view, name="logout"),
    url("^new_room/$", add_room, name="add_room"),
    url("^help/", help_view, name="help"),
    url("^profile/", profile_view, name="profile"),
    url("^room/(?P<room_id>\d+)/$", room, name="room"),
    url("^room/(?P<room_id>\d+)/auth/$", room_auth, name="room_auth"),
    url("^room/(?P<room_id>\d+)/enter/$", enter_room, name="enter_room"),
    url("^room/(?P<room_id>\d+)/settings/$", settings_room, name="settings_room"),
    url("^room/(?P<room_id>\d+)/change_description/$", modify_description, name="change_description"),
    url("^room/(?P<room_id>\d+)/change_password/$", change_password, name="change_password"),
    url("^room/(?P<room_id>\d+)/add_users/$", add_users, name="add_users"),
    url("^room/(?P<room_id>\d+)/place/$", place_room, name="place_room"),
    url("^room/(?P<room_id>\d+)/delete/$", delete_scenario, name="delete_scenario"),
    url("^room/(?P<room_id>\d+)/edit/$", edit_scenario, name="edit_scenario"),
    url("^room/(?P<room_id>\d+)/time/$", time_room, name="time_room"),
    url("^room/(?P<room_id>\d+)/result/$", result_room, name="result_room"),
    url("^room/(?P<room_id>\d+)/result/get/$", send_results, name="send_results"),
    url("^room/(?P<room_id>\d+)/new_place/$", add_place, name="add_place"),
    url("^room/(?P<room_id>\d+)/new_time/$", add_time, name="add_time"),
    url("^room/(?P<room_id>\d+)/place/new_answer/$", add_place_answer, name="add_place_answer"),
    url("^room/(?P<room_id>\d+)/time/new_answer/$", add_time_answer, name="add_time_answer"),
    url(r'^accounts/password_change/done/$', go_to_profile, name='password_change_done'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    {% block style %}{% endblock %}
</head>
<body>
{% block navbar %}
<nav class="navbar tiny_nav">
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <img src="{% static 'img/menu.svg' %}" alt="" id="menu_icon">
            </a>
            <ul class="dropdown-menu drop">
                <li><a href="{% url 'party:profile' %}">Профиль</a></li>
                <li><a href="{% url 'party:help' %}">Справка</a></li>
                <li><a href="{% url 'party:logout' %}">Выход</a></li>
            </ul>
        </li>
    </ul>
</nav>
{% endblock %}
{% block content %}
{% endblock %}
{% block footer %}
{% endblock %}
</body>
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
{% block script %}{% endblock %}
</html>