partisan/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^', include("party_rooms.urls", namespace="party")),
    url('^accounts/', include('django.contrib.auth.urls')),
    url(r'^registration/', include('registration.backends.simple.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^password/change/$', auth_views.password_change, name='password_change'),
]

party_rooms/urls.py
from django.conf.urls import url
from party_rooms.views import *
from party_rooms.ajax import *


urlpatterns = [
    url("^$", start_page, name="start_page"),
    url("^logout/", logout_view, name="logout"),
    url("^new_room/$", add_room, name="add_room"),
    url("^help/", help_view, name="help"),
    url("^profile/", profile_view, name="profile"),
    url("^room/(?P<room_id>\d+)/$", room, name="room"),
    url("^room/(?P<room_id>\d+)/auth/$", room_auth, name="room_auth"),
    url("^room/(?P<room_id>\d+)/enter/$", enter_room, name="enter_room"),
    url("^room/(?P<room_id>\d+)/settings/$", settings_room, name="settings_room"),
    url("^room/(?P<room_id>\d+)/change_description/$", modify_description, name="change_description"),
    url("^room/(?P<room_id>\d+)/change_password/$", change_password, name="change_password"),
    url("^room/(?P<room_id>\d+)/add_users/$", add_users, name="add_users"),
    url("^room/(?P<room_id>\d+)/place/$", place_room, name="place_room"),
    url("^room/(?P<room_id>\d+)/delete/$", delete_scenario, name="delete_scenario"),
    url("^room/(?P<room_id>\d+)/edit/$", edit_scenario, name="edit_scenario"),
    url("^room/(?P<room_id>\d+)/time/$", time_room, name="time_room"),
    url("^room/(?P<room_id>\d+)/result/$", result_room, name="result_room"),
    url("^room/(?P<room_id>\d+)/result/get/$", send_results, name="send_results"),
    url("^room/(?P<room_id>\d+)/new_place/$", add_place, name="add_place"),
    url("^room/(?P<room_id>\d+)/new_time/$", add_time, name="add_time"),
    url("^room/(?P<room_id>\d+)/place/new_answer/$", add_place_answer, name="add_place_answer"),
    url("^room/(?P<room_id>\d+)/time/new_answer/$", add_time_answer, name="add_time_answer"),
    url(r'^accounts/password_change/done/$', go_to_profile, name='password_change_done'),
]

party_rooms/models.py
from django.db import models
from django.contrib.auth.models import User
from party_rooms.logic import *


class Room(models.Model):
    usermade = models.BooleanField(default=True)
    room_users = models.ManyToManyField(User)
    admin_id = models.IntegerField(null=True)
    pass_hash = models.CharField(max_length=32, null=True)
    description = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.description

    def drop_caches(self):
        results = CachedResult.objects.filter(place__room_id=self.pk)
        Vote.mark_to_update(results)


class MeetingOption(models.Model):
    description = models.TextField(verbose_name="описание места")
    room = models.ForeignKey("Room")
    author_id = models.IntegerField(default=0)

    def __str__(self):
        return self.description

    class Meta:
        abstract = True
        unique_together = (("description", "room"),)


class MeetingTime(MeetingOption):
    pass


class MeetingPlace(MeetingOption):
    pass


class Conflict(models.Model):
    place = models.ForeignKey("MeetingPlace")
    time = models.ForeignKey("MeetingTime")


class Vote(models.Model):
    user = models.ForeignKey(User)
    possibility = models.IntegerField(choices=((UNDEFINED, "не задано"),
                                               (GOOD, "подходит"),
                                               (BAD, "не подходит"),
                                               (NOT_SURE, "возможно, подходит")),
                                      default=UNDEFINED)
    rating = models.IntegerField(choices=((UNDEFINED, "не задано"),
                                          (GOOD, "одобрительно"),
                                          (BAD, "неодобрительно"),
                                          (NOT_SURE, "нейтрально")),
                                 default=0)

    class Meta:
        abstract = True

    @staticmethod
    def mark_to_update(collection):
        for result in collection:
            result.need_calc = True
            result.save()


class PlaceVote(Vote):
    place = models.ForeignKey("MeetingPlace")

    def __str__(self):
        return "%s: %s" % (self.user, self.place)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(PlaceVote, self).save(force_insert, force_update, using, update_fields)
        self.mark_to_update(CachedResult.objects.filter(place=self.place))
        self.mark_to_update(UserCachedResult.objects.filter(user=self.user, place=self.place))


class TimeVote(Vote):
    time = models.ForeignKey("MeetingTime")

    def __str__(self):
        return "%s: %s" % (self.user, self.time)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(TimeVote, self).save(force_insert, force_update, using, update_fields)
        self.mark_to_update(CachedResult.objects.filter(time=self.time))
        self.mark_to_update(UserCachedResult.objects.filter(user=self.user, time=self.time))


class AbstractCachedResult(models.Model):
    need_calc = models.BooleanField(default=True)
    place = models.ForeignKey("MeetingPlace")
    time = models.ForeignKey("MeetingTime")
    result_rating = models.IntegerField(null=True)

    def get_room(self):
        return self.place.room

    class Meta:
        abstract = True


class CachedResult(AbstractCachedResult):
    participants = models.IntegerField(default=0)

    def calc(self):
        if self.need_calc:
            self.participants = 0
            self.result_rating = 0
            for user in self.get_room().room_users.all():
                user_result = UserCachedResult.objects.get_or_create(
                    user=user, place=self.place, time=self.time)[0].calc()
                self.result_rating += user_result.result_rating
                if user_result.is_possible:
                    self.participants += 1
            self.need_calc = False
            self.save()
        return self

    @staticmethod
    def update_all(room):
        for m_place in MeetingPlace.objects.filter(room=room):
            for m_time in MeetingTime.objects.filter(room=room):
                CachedResult.objects.get_or_create(place=m_place, time=m_time)[0].calc()

    class Meta:
        ordering = ["-result_rating"]


class UserCachedResult(AbstractCachedResult):
    is_possible = models.BooleanField(default=True)
    user = models.ForeignKey(User)

    def calc(self):
        if self.need_calc:
            place_vote = PlaceVote.objects.get_or_create(user=self.user, place=self.place)[0]
            time_vote = TimeVote.objects.get_or_create(user=self.user, time=self.time)[0]
            self.result_rating = calc_rating(place_vote, time_vote)
            self.is_possible = check_possibility(place_vote, time_vote)
            self.need_calc = False
            self.save()
        return self

party_rooms/forms.py
from django.forms import ModelForm
from registration.forms import RegistrationForm

from party_rooms.models import Room, User


class RoomForm(ModelForm):
    class Meta:
        model = Room
        exclude = []


class UserSettingsForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

party_rooms/views.py
import hashlib
import operator
from functools import reduce

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.views.decorators.http import require_POST

from party_rooms.forms import *
from party_rooms.models import Room, PlaceVote, TimeVote, User
from party_rooms.view_decorators import basic_view, find_room, check_room_auth


@login_required
@basic_view('party_rooms/all_rooms.html')
def start_page(request):
    return {'room_list': request.user.room_set.all}


@login_required
def add_room(request):
    if request.method == 'POST':
        description = request.POST['description']
        pass_hash = hashlib.md5(request.POST['password'].encode('utf-8')).hexdigest()
        new_room = Room.objects.create(pass_hash=pass_hash,
                                       description=description,
                                       admin_id=request.user.pk
                                       )
        new_room.room_users.add(request.user)
        new_room.save()
        return HttpResponseRedirect(reverse('party:room', kwargs={'room_id': new_room.pk}))
    else:
        return HttpResponseRedirect(reverse('party:start_page'))


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_generic.html')
def room(request, current_room):
    return {'room': current_room,
            'is_admin': (request.user.pk == current_room.admin_id)}


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_settings.html')
def settings_room(request, current_room):
    return {'room': current_room,
            'is_admin': (request.user.pk == current_room.admin_id),
            'form': RoomForm(instance=current_room),
            'possible_users': get_possible_users(current_room)}


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_for_place.html')
def place_room(request, current_room):
    def answer(offer):
        return offer, get_or_none(PlaceVote, user=request.user, place=offer)
    return {'room': current_room,
            'options': map(answer, current_room.meetingplace_set.all()),
            'is_admin': (request.user.pk == current_room.admin_id)}


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_for_time.html')
def time_room(request, current_room):
    def answer(offer):
        return offer, get_or_none(TimeVote, user=request.user, time=offer)
    return {'room': current_room,
            'options': map(answer, current_room.meetingtime_set.all()),
            'is_admin': (request.user.pk == current_room.admin_id)}


@login_required
@find_room
@check_room_auth
@basic_view('party_rooms/room_for_result.html')
def result_room(request, current_room):
    return {'room': current_room,
            'is_admin': (request.user.pk == current_room.admin_id)}


@login_required
@find_room
@basic_view('party_rooms/room_auth.html')
def room_auth(request, current_room):
    if request.user in current_room.room_users.all():
        return HttpResponseRedirect(reverse('party:room', kwargs={'room_id': current_room.pk}))
    return {'room': current_room}


@login_required
@require_POST
@find_room
def enter_room(request, current_room):
    if 'password' in request.POST:
        hash_sum = hashlib.md5(request.POST['password'].encode('utf-8')).hexdigest()
        if current_room.pass_hash == hash_sum:
            current_room.room_users.add(request.user)
            current_room.drop_caches()
            return HttpResponseRedirect(reverse('party:room', kwargs={'room_id': current_room.pk}))
    return HttpResponseRedirect(reverse('party:room_auth', kwargs={'room_id': current_room.pk}))


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('party:start_page'))


def go_to_profile(request):
    return HttpResponseRedirect(reverse('party:profile'))


@login_required
@basic_view("party_rooms/help.html")
def help_view(request):
    return {}


@login_required
@basic_view("party_rooms/profile.html")
def profile_view(request):
    if request.method == "POST":
        form = UserSettingsForm(request.POST, instance=request.user)
        try:
            form.save()
            return {"saved": True, "form": form}
        except ValueError:
            return {"saved": False, "form": form}
    return {"saved": False, "form": UserSettingsForm(instance=request.user)}


def get_or_none(model, *args, **kwargs):
    try:
        return model.objects.get(*args, **kwargs)
    except model.DoesNotExist:
        return None


@login_required
@require_POST
@find_room
def add_users(request, current_room):
    if request.user.pk == current_room.admin_id:
        try:
            for user_id in request.POST['users']:
                user = User.objects.get(pk=int(user_id))
                current_room.room_users.add(user)
            current_room.drop_caches()
        except (KeyError, User.DoesNotExist):
            pass
    return HttpResponseRedirect(reverse('party:settings_room',  kwargs={'room_id': current_room.pk}))


def get_possible_users(current_room):
    def make_set(from_room):
        return set(from_room.room_users.all())
    admin = User.objects.get(pk=current_room.admin_id)
    user_set = reduce(operator.or_, map(make_set, admin.room_set.all()))
    return user_set.difference(set(current_room.room_users.all()))

templates/party_rooms/fragment/modal_add_place.html
{% extends 'party_rooms/fragment/modal_base.html' %}
{% block modal_id %}new_place_modal{% endblock %}

{% block modal_title %}
    Предложить место
{% endblock %}

{% block modal_content %}
    <form action="{% url 'party:add_place' room.pk %}" method="post" id="new_place_form">
        {% csrf_token %}
        <p></p>
        <textarea name="description" class="form_description"></textarea>
    </form>
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
    <button type="button" class="btn btn-primary" onclick="add_from_modal('#new_place_form', empty_description)">Сохранить изменения</button>
{% endblock %}

templates/party_rooms/fragment/modal_add_time.html
{% extends 'party_rooms/fragment/modal_base.html' %}
{% block modal_id %}new_time_modal{% endblock %}

{% block modal_title %}
    Предложить время
{% endblock %}

{% block modal_content %}
    <form action="{% url 'party:add_time' room.pk %}" method="post" id="new_time_form">
        {% csrf_token %}
        <p></p>
        <div class="form-group">
            <div class='input-group date' id='dtpicker'>
                <input type='text' class="form-control" name="time" placeholder="Выберите время"/>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        <div class="form-group">
            <label for="time_desc">Комментарий:</label>
            <textarea id="time_desc" name="description" class="form_description"></textarea>
        </div>

    </form>
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
    <button type="button" class="btn btn-primary" onclick="add_from_modal('#new_time_form', empty_time)">Сохранить изменения</button>
{% endblock %}

templates/party_rooms/fragment/modal_base.html
<div id="{% block modal_id %}{% endblock %}" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">
                    {% block modal_title %}{% endblock %}
                </h4>
            </div>
            <div class="modal-body">
                {% block modal_content %}{% endblock %}
            </div>
        <div class="modal-footer">
            {% block modal_footer %}{% endblock %}
      </div>
    </div>
  </div>
</div>

templates/party_rooms/fragment/modal_change_description.html
{% extends 'party_rooms/fragment/modal_base.html' %}
{% block modal_id %}change_description_modal{% endblock %}

{% block modal_title %}
    Изменить описание комнаты
{% endblock %}

{% block modal_content %}
    <form action="{% url 'party:change_description' room.pk %}" method="post" id="change_description_form">
        {% csrf_token %}
        <textarea name="description" class="form_description">{{ room.description }}</textarea>
    </form>
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
    <button type="button" class="btn btn-primary" onclick="change_from_modal('#change_description_form')">Сохранить изменения</button>
{% endblock %}

templates/party_rooms/fragment/modal_change_password.html
{% extends 'party_rooms/fragment/modal_base.html' %}
{% block modal_id %}change_password_modal{% endblock %}

{% block modal_title %}
    Изменить пароль комнаты
{% endblock %}

{% block modal_content %}
    <form action="{% url 'party:change_password' room.pk %}" method="post" id="change_password_form">
        {% csrf_token %}
        <p></p>
        <input type="password" placeholder="новый пароль" name="password1">
        <input type="password" placeholder="повторите пароль" name="password2">
    </form>
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
    <button type="button" class="btn btn-primary" onclick="add_from_modal('#change_password_form', correct_passwords)">Сохранить изменения</button>
{% endblock %}

templates/party_rooms/fragment/modal_delete_scenario.html
{% extends 'party_rooms/fragment/modal_base.html' %}
{% block modal_id %}delete_scenario_modal{% endblock %}

{% block modal_title %}
    Подтвердите удаление
{% endblock %}

{% block modal_content %}
    <form action="{% url 'party:delete_scenario' room.pk %}" method="post" id="delete_form">
        {% csrf_token %}
        <p></p>
        <input type="text" name="option_id" class="hidden">
        <input type="text" name="option_type" class="hidden">
    </form>
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
    <button type="button" class="btn btn-danger" onclick="add_from_modal('#delete_form')">Удалить</button>
{% endblock %}

templates/party_rooms/fragment/modal_edit_scenario.html
{% extends 'party_rooms/fragment/modal_base.html' %}
{% block modal_id %}edit_scenario_modal{% endblock %}

{% block modal_title %}
    Внесение изменений
{% endblock %}

{% block modal_content %}
    <form action="{% url 'party:edit_scenario' room.pk %}" method="post" id="edit_form">
        {% csrf_token %}
        <p></p>
        <textarea class="form_description" name="description"></textarea>
        <input type="text" name="option_id" class="hidden">
        <input type="text" name="option_type" class="hidden">
    </form>
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
    <button type="button" class="btn btn-primary" onclick="add_from_modal('#edit_form', empty_description)">Сохранить</button>
{% endblock %}

templates/party_rooms/fragment/modal_enter_room.html
{% extends 'party_rooms/fragment/modal_base.html' %}
{% block modal_id %}enter_room_modal{% endblock %}

{% block modal_title %}
Вход в комнату
{% endblock %}

{% block modal_content %}
    <form method="post" id="enter_room_form">
        {% csrf_token %}
        <p>Введите номер комнаты и пароль, который Вам сообщили при приглашении</p>
        <input type="text" placeholder="Номер комнаты" id="enter_room_number">
        <input type="password" placeholder="Пароль" name="password" id="room_password">
    </form>
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
    <button type="button" class="btn btn-primary" onclick="enter_room()">Вход</button>
{% endblock %}

templates/party_rooms/fragment/modal_invite_user.html
{% extends 'party_rooms/fragment/modal_base.html' %}
{% block modal_id %}invite_user_modal{% endblock %}

{% block modal_title %}
    Пригласить пользоватей из других комнат
{% endblock %}

{% block modal_content %}
    <form action="{% url 'party:add_users' room.pk %}" method="post" id="invite_user_form">
        {% csrf_token %}
        <select name="users" class="selectpicker" multiple data-width="fit"
                data-live-search="true" title="Выберите одного или нескольких пользователей">
            {% for user in possible_users %}
            <option data-content="{{ user.get_full_name|default:user.username }}">{{ user.pk }}</option>
            {% endfor %}
        </select>
    </form>
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
    <button type="button" class="btn btn-primary" onclick="add_from_modal('#invite_user_form')">Сохранить изменения</button>
{% endblock %}

templates/party_rooms/fragment/modal_new_room.html
{% extends 'party_rooms/fragment/modal_base.html' %}
{% block modal_id %}new_room_modal{% endblock %}

{% block modal_title %}
    Создание новой комнаты
{% endblock %}

{% block modal_content %}
    <form action="{% url 'party:add_room' %}" method="post" id="new_room_form">
        {% csrf_token %}
        <p>Задайте пароль для новых участников</p>
        <input type="password" name="password" placeholder="пароль" id="passw1">
        <input type="password" placeholder="повторите пароль" id="passw2">
        <p>и описание комнаты:</p>
        <textarea name="description" class="form_description"></textarea>
    </form>
{% endblock %}

{% block modal_footer %}
    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
    <button type="button" class="btn btn-primary" onclick="make_room()">Сохранить изменения</button>
{% endblock %}

templates/party_rooms/fragment/opinion_widget.html
<div class="row entry">
    <div class="btn btn-default entry_description_short col-xs-9">
            <p class="text-left">
                {{ option.description|default:'не задано' }}
            </p>
            <i class="fa fa-angle-down spoiler" onclick="description_click(this.closest('div'))"></i>
        {% if is_admin or option.author_id == request.user.pk %}
            <div class="admin_options">
                <button class="admin_option edit_option" onclick="edit_option_dialog({{ option.pk }}, this)"><i class="fa fa-edit fa-align-center"></i></button>
                <button class="admin_option remove_option" onclick="remove_option_dialog({{ option.pk }}, this)"><i class="fa fa-trash fa-align-center"></i></button>
            </div>
        {% endif %}
    </div>
    <div class="choices col-xs-3">
        <div class="btn-group btn-group-lg" role="group" data-selected="{{ choice.possibility|default:'0' }}" data-type="possibility" data-id="{{ option.pk }}">
            <button type="button" class="btn" onclick="choice_click(this, 1)" title="Не смогу прийти"><i class="fa fa-times-circle"></i></button>
            <button type="button" class="btn" onclick="choice_click(this, 2)" title="Возможно, смогу прийти"><i class="fa fa-question-circle"></i></button>
            <button type="button" class="btn" onclick="choice_click(this, 3)" title="Смогу прийти"><i class="fa fa-check-circle"></i></button>
        </div>
        <br>
        <div class="btn-group btn-group-lg" role="group" data-selected="{{ choice.rating|default:'0' }}" data-type="rating" data-id="{{ option.pk }}">
            <button type="button" class="btn" onclick="choice_click(this, 1)" title="Идея не нравится"><i class="fa fa-frown-o"></i></button>
            <button type="button" class="btn" onclick="choice_click(this, 2)" title="Нейтрально отношусь"><i class="fa fa-meh-o"></i></button>
            <button type="button" class="btn" onclick="choice_click(this, 3)"  title="Отличная идея!"><i class="fa fa-smile-o"></i></button>
        </div>
    </div>
</div>

templates/party_rooms/fragment/room_help_message.html
<div>
    <h3>Об использовании комнат:</h3>
    <p>После перехода на одну из вкладок комнаты вы сможете выразить своё мнение по поводу предстоящей встречи.</p>
    <p>Это можно сделать 2 способами:</p>
    <p>1. Предложить свой вариант времени или места</p>
    <p>2. Оценить уже предложенный вариант</p>
    <p>Критерии оценивания:</p>
    <div>
        <p><button class="btn btn-default help-icon" data-hover="btn-success">
            <i class="fa fa-check-circle"></i>
        </button> Смогу присутствовать</p>
        <p><button class="btn btn-default help-icon" data-hover="btn-primary">
            <i class="fa fa-question-circle"></i>
        </button> Возможно, смогу присутствовать</p>
        <p><button class="btn btn-default help-icon" data-hover="btn-danger">
            <i class="fa fa-times-circle"></i>
        </button> Не смогу присутствовать</p>
        <p><button class="btn btn-default help-icon" data-hover="btn-success">
            <i class="fa fa-frown-o"></i>
        </button> Идея нравится</p>
        <p><button class="btn btn-default help-icon" data-hover="btn-primary">
            <i class="fa fa-meh-o"></i>
        </button> Нейтрально отношусь</p>
        <p><button class="btn btn-default help-icon" data-hover="btn-danger">
            <i class="fa fa-frown-o"></i>
        </button> Идея не нравится</p>
    </div>
</div>
<script>
    $(".help-icon").hover(
        function () {
            $(this).removeClass("btn-default");
            $(this).addClass($(this).data("hover"));
        },
        function () {
            $(this).removeClass($(this).data("hover"));
            $(this).addClass("btn-default");
        }
    );
</script>